version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: decision-service-postgres
    environment:
      POSTGRES_DB: decision_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - decision-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decision-service-app
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/decision_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      API_TOKEN: test-token-12345
      ENCRYPTION_KEY: test-32-char-encryption-key-test
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - decision-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  decision-network:
    driver: bridge