server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/decision_service_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
  
  jpa:
    hibernate:
      ddl-auto: update  # Auto-create/update tables
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  cache:
    type: simple
  
  mail:
    host: localhost
    port: 1025
    test-connection: false
  
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    property-naming-strategy: SNAKE_CASE

app:
  mail:
    default-from: local@decisionservice.local
  encryption:
    key: local-32-char-encryption-key-test
  decision:
    auto-approve-threshold: 10000
    max-loan-amount: 100000

api:
  token: test-token-12345

logging:
  level:
    com.decisionservicemaster: DEBUG
    org.hibernate.SQL: DEBUG

debug: false